### PR TITLE
Update link, :hover and :active colours

### PR DESCRIPTION
**Pull request by russellthorn**
This pull request updates colours for links, :hover and :active selectors.

Colours should be managed and kept in 1 place in the frontend toolkit. This means they are easier to manage in 1 place and use variables which makes them far more flexible.

### CODE REVIEW

**Comment by rpowis** [comment]
@russellthorn should these not be replaced with whatever [these variables resolve to](https://github.com/alphagov/govuk_template/blob/master/source/assets/stylesheets/_basic.scss#L81-L95) rather than straight up removed?

**Comment by rpowis** [comment]
Looks like they end up coming from [govuk_frontend_toolkit](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/colours/_palette.scss#L58-L61) as you say...
```
$govuk-blue: #005ea5;
$light-blue: #2b8cc4;

$link-colour: $govuk-blue;
$link-active-colour: $light-blue;
$link-hover-colour: $light-blue;
$link-visited-colour: #4c2c92;
```

**Comment by russellthorn** [comment]
Aha, you beat me to it :)

Yep, FE toolkit holds all the colours we need https://github.com/hmrc/assets-frontend/blob/master/assets/govuk_frontend_toolkit/stylesheets/_colours.scss

**Comment by rpowis** [comment]
But removing them from here doesn't explicitly use them. We only use them in our frontends because we _happen_ to include assets-frontend (which has toolkit compiled into it) and the template styles.

I think to follow the explicit setting of link colours the same way GOV.UK does we should update the colours here rather than remove them.

**Pull request merged**
